/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bubble: typeof import('./components/Bubble.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    Icon: (typeof import('./components/Icon.vue'))['default']
    Render: typeof import('./components/Render.vue')['default']
    Sender: typeof import('./components/Sender.vue')['default']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
  }
}
